import json
p='docs/drafts/draft-sosiologi-k12-v1-bab2.json'
d=json.load(open(p)); b=d['bab'][0]
SRC='Bank Soal Sukses TKA 26 Sosiologi (@my99dreams) — 02 Latihan no. %s (kunci & pembahasan detail dari 08 Pembahasan hlm. 94-95: %s); transkrip verbatim'
Q=[
 {'soal':'Kakak membeli alat makan karakter karena melihat iklan dan mendapatkan diskon yang tinggi. Jika dilihat dari faktor yang memengaruhi interaksi sosial, sikap kakak termasuk bagian ....','tipe':'pg',
  'opsi':['sugesti.','motivasi.','imitasi.','empati.','identifikasi.'],'jawaban':0,
  'pembahasan':'Faktor yang memengaruhi interaksi sosial salah satunya SUGESTI: pemberian suatu pandangan atau pengaruh oleh seseorang kepada orang lain. Contohnya membeli barang karena melihat iklan dan adanya diskon atau potongan harga — penerimaan pandangan tanpa analisis panjang. Imitasi berarti meniru sikap/tindakan secara langsung; empati ikut merasakan; identifikasi menjadi sama persis — tidak tampil pada kasus.',
  'sumber':SRC%('1','A')},
 {'soal':'Seorang guru dan seorang murid sedang berdiskusi tentang materi pelajaran sosiologi di perpustakaan. Jika dilihat dari jenis-jenis interaksi sosial termasuk bagian ....','tipe':'pg',
  'opsi':['hanya sendirian.','individu dengan kelompok.','individu dengan individu.','antarorganisasi.','antarkelompok.'],'jawaban':2,
  'pembahasan':'Berdasarkan pernyataan tersebut terjadi interaksi INDIVIDU dengan INDIVIDU: interaksi dilakukan oleh dua orang (guru dan murid) yang saling menanggapi dalam diskusi.',
  'sumber':SRC%('2','C')},
 {'soal':'Suatu pekerjaan jika dilakukan bersama akan cepat selesai. Kerja sama merupakan bagian dari bentuk interaksi sosial ....','tipe':'pg',
  'opsi':['disosiatif.','kolaboratif.','asimilasi.','asosiatif.','akomodasi.'],'jawaban':3,
  'pembahasan':'Bentuk-bentuk interaksi sosial salah satunya kerja sama (cooperation): beberapa ahli sosiologi menganggap adanya kerja sama sedikit membantu sebuah tim dalam menyelesaikan pekerjaan — contohnya kerja sama mengadakan kegiatan bakti sosial. Kerja sama masuk keluarga ASOSIATIF (positif, menyatukan).',
  'sumber':SRC%('3','D')},
 {'soal':'Mengucapkan terima kasih kepada orang lain karena telah membantunya merupakan bagian dari tingkatan norma sosial ....','tipe':'pg',
  'opsi':['adat istiadat.','hukum.','instrumental.','kerja sama.','cara.'],'jawaban':4,
  'pembahasan':'Satu di antara tingkatan norma sosial adalah CARA (usage): kebiasaan umum masyarakat yang berarti perbuatan pribadi — contohnya mengucapkan terima kasih karena telah dibantu. Bukan adat istiadat (tradisi kuat), bukan hukum (tertulis resmi).',
  'sumber':SRC%('4','E')},
 {'soal':'Belanja terkadang bisa dilakukan secara langsung (offline) dan secara tidak langsung (online). Dilihat dari syarat interaksi sosial termasuk bagian ....','tipe':'pg',
  'opsi':['komunikasi sosial.','kontak sosial.','tindakan instrumental.','nilai dominan.','nilai material.'],'jawaban':1,
  'pembahasan':'Satu di antara syarat interaksi sosial adalah KONTAK sosial: bisa terjadi secara langsung (primer) maupun tidak langsung (sekunder) — contohnya belanja online ataupun offline.',
  'sumber':SRC%('5','B')},
 {'soal':'Bentuk interaksi sosial terdapat bentuk disosiatif. Berikut yang termasuk bentuk disosiatif adalah ....','tipe':'pg',
  'opsi':['akulturasi.','asimilasi.','kontravensi.','kerja sama.','akomodasi.'],'jawaban':2,
  'pembahasan':'Bentuk disosiatif salah satunya KONTRAVENSI: berada antara persaingan dan konflik, berisi hal negatif seperti menyebar desas-desus atau gosip, kekerasan tersembunyi. Akulturasi/asimilasi/kerja sama/akomodasi = asosiatif.',
  'sumber':SRC%('6','C')},
 {'soal':'Terdapat tradisi pernikahan di suatu wilayah tentunya berbeda-beda. Berdasarkan tingkatan norma sosial termasuk pada bagian ....','tipe':'pg',
  'opsi':['hukum (law).','adat istiadat (customs).','tindakan afeksi.','tindakan modern.','cara (usage).'],'jawaban':1,
  'pembahasan':'Pada tingkatan norma sosial terdapat ADAT ISTIADAT (customs): norma yang paling kuat dalam tradisi masyarakat — contohnya adat atau tradisi pernikahan dalam suatu wilayah.',
  'sumber':SRC%('7','B')},
 {'soal':'Fenomena bahasa gaul terkadang memudahkan sebagian masyarakat dalam berkomunikasi; fenomena ini menggunakan bahasa yang baik ataupun sedikit kasar. Maka perilaku tersebut termasuk pada ....','tipe':'pg',
  'opsi':['integrasi sosial.','difusi sosial.','disosiatif interaksi sosial.','asimilasi budaya.','akulturasi budaya.'],'jawaban':2,
  'pembahasan':'Dilihat dari interaksi sosial, bahasa gaul termasuk bentuk DISOSIATIF: sebagian masyarakat menggunakan bahasa gaul yang berisi sebagian kata-kata kasar yang menyimpang pada aturan yang berlaku (kontravensi terhadap norma kesopanan).',
  'sumber':SRC%('8','C')},
 {'soal':'Sebuah wilayah Z mengalami konflik sosial yang rumit sehingga membutuhkan penyelesaian konflik tersebut. Cara yang tepat dalam penyelesaian konflik tersebut adalah ....','tipe':'pg',
  'opsi':['akomodasi.','kontravensi.','difusi sosial.','akulturasi.','asimilasi.'],'jawaban':0,
  'pembahasan':'Berdasarkan fenomena tersebut termasuk bentuk interaksi sosial ASOSIATIF pada AKOMODASI: bentuk penyelesaian konflik sosial — contohnya mediasi yang menggunakan pihak ketiga sebagai penengah atau penasihat.',
  'sumber':SRC%('9','A')},
 {'soal':'Terjadinya kasus bullying di beberapa wilayah menjadikan seseorang lebih berhati-hati dalam bertindak. Berdasarkan bentuk interaksi sosial termasuk pada bagian .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['disosiatif.','akulturasi.','asimilasi.','konflik sosial.','difusi sosial.'],'jawaban':[0,3],
  'pembahasan':'Opsi A dan D merupakan bagian dari interaksi sosial disosiatif: bullying = konflik sosial yang bersifat merusak, merugikan, dan harus dihindari. Akulturasi/asimilasi = asosiatif; difusi sosial bukan bentuk interaksi.',
  'sumber':SRC%('10','A,D')},
 {'soal':'Pada daya ikat norma sosial terdapat beberapa tahap di antaranya .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['mendarah daging (internalized value).','kebiasaan (folkways).','adat istiadat (customs).','tata kelakuan (mores).','keajegan sosial.'],'jawaban':[1,2,3],
  'pembahasan':'Daya ikat norma sosial: (1) cara (usage) — kebiasaan umum, mis. menerima kasih sayang, minta tolong, minta maaf; (2) kebiasaan (folkways) — tindakan berulang-ulang, mis. memberi salam kepada orang tua; (3) tata kelakuan (mores) — kebiasaan bernilai moral tinggi, mis. setia dalam pernikahan; (4) adat istiadat (customs) — norma mengikat kuat dalam tradisi, mis. upacara adat pernikahan; (5) hukum (law) — tertulis resmi, mis. UUD 1945. Maka yang tepat: folkways, customs, mores (B, C, D).',
  'sumber':SRC%('11','B,C,D')},
 {'soal':'Tindakan sosial yang dilakukan oleh semua masyarakat tentunya berbeda-beda. Berikut yang termasuk pada tindakan sosial menurut Max Weber adalah .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['tindakan afeksi.','tindakan berorientasi instrumental.','tindakan berorientasi nilai.','tindakan modern.','tindakan kontemporer.'],'jawaban':[0,1,2],
  'pembahasan':'Tindakan sosial menurut Max Weber: (1) berorientasi instrumental — dilakukan atas dasar tujuan & manfaat yang dihitung, mis. kakak belajar sungguh-sungguh untuk lulus PTN favorit; (2) berorientasi nilai — demi nilai yang diyakini, mis. membeli sepatu karena murah dan berkualitas; (3) tradisional — adat/kebiasaan, mis. membungkuk saat menyapa orang tua; (4) afeksi — emosi/perasaan spontan, mis. kasih sayang atau marah. "Modern/kontemporer" bukan kategori Weber.',
  'sumber':SRC%('12','A,B,C')},
 {'soal':'Pada dasarnya manusia membutuhkan suatu nilai sosial dan norma sosial agar hidupnya lebih terarah. Berikut yang termasuk pada jenis nilai sosial menurut Prof. Dr. Notonegoro adalah .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['nilai kerohanian.','nilai dominan.','nilai material.','nilai vital.','nilai mendarah daging.'],'jawaban':[0,2,3],
  'pembahasan':'Nilai sosial menurut Notonegoro: (1) nilai MATERIAL — bermanfaat bagi kebutuhan jasmani, mis. makan, minum, pakaian; (2) nilai VITAL — bermanfaat untuk mendukung aktivitas, mis. kendaraan; (3) nilai KEROHANIAN — nilai spiritual untuk kebutuhan jiwa/batin. "Dominan" & "mendarah daging" bukan kategori Notonagoro.',
  'sumber':SRC%('13','A,C,D')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: manusia tidak dapat hidup seorang diri karena membutuhkan bantuan sesama (makhluk sosial); interaksi sosial masyarakat memiliki bentuk asosiatif dan disosiatif. Berikut yang termasuk bentuk ASOSIATIF adalah ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['Adanya akulturasi atau percampuran dua kebudayaan tanpa menghilangkan kebudayaan asli.','Adanya kontravensi seperti menyebarkan gosip atau desas-desus.','Adanya akomodasi yang berarti upaya penyelesaian konflik sosial yang terjadi di masyarakat.'],
  'jawaban':[0,1,0],
  'pembahasan':'BENAR: akulturasi = percampuran dua kebudayaan tanpa menghilangkan budaya asli (asosiatif), contoh Menara Kudus di Jawa Tengah (percampuran budaya Islam dan Hindu). SALAH: kontravensi = disosiatif (negatif), contoh menyebarkan gosip/desas-desus. BENAR: akomodasi = upaya penyelesaian konflik (asosiatif), contoh ajudikasi lewat jalur pengadilan atau jalur hukum.',
  'sumber':SRC%('19','B,S,B')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: interaksi sosial akan berjalan baik jika ada dua hal yang menjadi satu. Berikut yang termasuk SYARAT interaksi sosial adalah ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['Adanya pengebaian nilai dan norma sosial oleh masyarakat.','Terdapat kontak sosial di masyarakat.','Terdapat komunikasi sosial untuk menyampaikan segala pesan.','Terjadinya konflik sosial di masyarakat.'],
  'jawaban':[1,0,0,1],
  'pembahasan':'SALAH: "pengebawaian nilai dan norma" bukan syarat interaksi (itu sosialisasi). BENAR: KONTAK sosial = syarat terjadinya interaksi, pihak berhubungan langsung maupun tidak. BENAR: KOMUNIKASI sosial = syarat interaksi, menyampaikan pesan dan mendapat tanggapan/lahiran sinyal. SALAH: konflik bukan syarat interaksi — justru konflik adalah bagian bentuk disosiatif.',
  'sumber':SRC%('20','S,B,B,S')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: dalam kehidupan sehari-hari manusia berpegang teguh pada nilai dan norma; berdasarkan DAYA IKAT norma, pernyataan berikut ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['Adanya akomodasi sosial di masyarakat yang mencegah terjadinya konflik sosial.','Terdapat cara (usage) yang menunjukkan pada suatu bentuk perbuatan pribadi.','Memberikan batasan-batasan pada perilaku individu dan menjaga solidaritas.','Terjadinya kontravensi dalam kehidupan masyarakat.'],
  'jawaban':[1,0,0,1],
  'pembahasan':'SALAH: akomodasi adalah bentuk interaksi (penyelesaian konflik), BUKAN tingkat daya ikat norma. BENAR: cara (usage) = daya ikat norma yang menunjukkan perbuatan pribadi. BENAR: tata kelakuan (mores) = pengawasan baik langsung maupun tidak, memberi batasan perilaku individu dan menjaga solidaritas antar anggota. SALAH: kontravensi = bentuk disosiatif yang memicu konflik, bukan daya ikat norma.',
  'sumber':SRC%('23','S,B,B,S')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: dengan adanya norma sosial kehidupan manusia berpegang teguh pada sebuah aturan. Berikut yang termasuk bagian dari NORMA SOSIAL adalah ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['Dalam interaksi sosial tentunya membutuhkan komunikasi yang baik agar terciptanya kehidupan yang selaras.','Sebuah aturan yang tertulis dan juga bersifat resmi.','Aturan sosial yang muncul dari tindakan yang dilakukan berulang-ulang dalam suatu masyarakat.','Suatu aturan yang bersifat mutlak dan bersumber dari Tuhan.'],
  'jawaban':[1,0,0,0],
  'pembahasan':'SALAH: komunikasi yang baik = syarat interaksi sosial, bukan jenis norma. BENAR: norma HUKUM = aturan tertulis, resmi, berisi perintah/larangan, ada sanksi bagi pelanggar. BENAR: norma KEBIASAAN = daya ikat dari tindakan berulang-ulang dalam masyarakat. BENAR: norma AGAMA = daya ikat mutlak, sumber dari Tuhan, tidak bisa ditawar.',
  'sumber':SRC%('24','S,B,B,B')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: interaksi sosial penting dalam masyarakat; dengan berinteraksi yang baik, masyarakat bertindak baik pula. Berikut yang termasuk TINDAKAN SOSIAL menurut Max Weber adalah ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['Tindakan yang dilakukan seseorang dengan memperhitungkan kesesuaian antara cara yang digunakan dengan tujuan yang akan dicapai.','Tindakan yang dilakukan dengan memperhitungkan manfaatnya.','Tindakan yang dilakukan pada dorongan emosional atau perasaan.','Sebuah cara untuk memengaruhi orang lain untuk melakukan suatu hal atau tindakan.'],
  'jawaban':[0,0,0,1],
  'pembahasan':'BENAR: kesesuaian cara-tujuan = tindakan rasional instrumental. BENAR: memperhitungkan manfaat = rasional instrumental/nilai. BENAR: dorongan emosional/perasaan = tindakan afeksi. SALAH: "cara memengaruhi orang lain" adalah definisi sugesti/komunikasi, BUKAN kategori tindakan sosial Weber.',
  'sumber':SRC%('25','B,B,B,S')},
 {'soal':'Pasangkan setiap tingkat daya ikat norma dengan contoh perilakunya yang paling tepat!','tipe':'jodoh',
  'premis':['Cara (usage)','Kebiasaan (folkways)','Tata kelakuan (mores)','Adat istiadat (customs)','Hukum (law)'],
  'opsi':['Mengucapkan terima kasih setelah dibantu','Memberi salam kepada orang tua setiap bertemu','Setia dalam pernikahan','Upacara adat pernikahan di suatu wilayah','Ditilang karena melanggar lampu lalu lintas'],
  'jawaban':[0,1,2,3,4],
  'pembahasan':'Urutan tangga daya ikat: usage (perbuatan pribadi sekali waktu) -> folkways (berulang) -> mores (moral tinggi) -> customs (tradisi mengikat) -> law (tertulis, sanksi tegas). Contoh-contoh di atas persis mengikuti urutan itu.',
  'sumber':'Gemilang Drill (latihan orisinal sistem — format menjodohkan tangga norma)'},
 {'soal':'Tokoh sosiologi yang mendefinisikan interaksi sosial sebagai hubungan sosial yang berkaitan dengan hubungan antarindividu, antarkelompok yang saling memengaruhi adalah ....','tipe':'isian',
  'jawaban':'Soerjono Soekanto','hintFormat':'Tulis nama tokoh, contoh: Max Weber',
  'pembahasan':'Menurut Soerjono Soekanto, interaksi sosial adalah hubungan sosial yang berkaitan dengan hubungan antarindividu, antarkelompok yang saling memengaruhi; norma sosial menurut beliau = bentuk nyata nilai sosial sebagai alat pengendali sosial.',
  'sumber':'Gemilang Drill (latihan orisinal sistem — isian tokoh definisi)'},
]
b['ujiPemahaman']=Q
json.dump(d,open(p,'w'),ensure_ascii=False,indent=2)
from collections import Counter
print('soal bab2 sosiologi:',len(Q),Counter(k['tipe'] for k in Q))
