import json
p='docs/drafts/draft-sosiologi-k12-v1-bab1.json'
d=json.load(open(p)); b=d['bab'][0]
SRC='Bank Soal Sukses TKA 26 Sosiologi (@my99dreams) — 01 Latihan no. %s (kunci diverifikasi dari 08 Pembahasan: %s); transkrip verbatim'
DR='Gemilang Drill (latihan orisinal sistem — %s)'
Q=[
 {'soal':'Tidak mempersoalkan baik atau buruknya fakta tetapi fakta tersebut harus tetap dianalisis disebut dengan ciri ilmu sosiologi bagian ....','tipe':'pg',
  'opsi':['nonetis.','modern.','klasik.','kontemporer.','sementara.'],'jawaban':0,
  'pembahasan':'Ciri sosiologi yang tidak mempersoalkan baik atau buruk suatu fakta disebut NONETIS: sosiologi hanya menjelaskan dan menganalisis fenomena sosial secara objektif tanpa penilaian moral — misalnya meneliti kriminalitas tanpa menilai pelaku "jahat", tetapi fokus pada faktor penyebabnya.',
  'sumber':SRC%('1','A')},
 {'soal':'Berikut fungsi dari ilmu sosiologi adalah ....','tipe':'pg',
  'opsi':['penyebab terjadinya konflik sosial.','sebagai perencanaan sosial.','tidak terjadinya komunikasi.','terdapat pengaruh dari globalisasi.','adanya kesenjangan ekonomi.'],'jawaban':1,
  'pembahasan':'Sosiologi berfungsi dalam PERENCANAAN SOSIAL: membantu merancang kebijakan yang tepat berdasarkan kondisi masyarakat. Pilihan lain adalah fenomena sosial, bukan fungsi ilmu.',
  'sumber':SRC%('2','B')},
 {'soal':'Kata socius dalam sosiologi yang berarti ....','tipe':'pg',
  'opsi':['tetangga.','teman.','kelompok.','organisasi.','korporasi.'],'jawaban':1,
  'pembahasan':'Socius (Latin) berarti teman atau kawan; logos (Yunani) berarti ilmu. Sosiologi = ilmu tentang hubungan antarmanusia dalam masyarakat.',
  'sumber':SRC%('3','B')},
 {'soal':'Berikut pengertian ilmu sosiologi adalah ....','tipe':'pg',
  'opsi':['usaha untuk menentang pihak lawan.','hubungan timbal balik.','suatu perubahan yang mendunia.','ilmu yang mempelajari tentang masyarakat.','suatu peraturan dalam masyarakat.'],'jawaban':3,
  'pembahasan':'Definisi umum sosiologi: ilmu yang mempelajari masyarakat, hubungan sosial, dan interaksi manusia — definisi paling tepat di antara opsi lain.',
  'sumber':SRC%('4','D')},
 {'soal':'Sosiologi sebagai ilmu yang terpisah dari fisika, filsafat, dan psikologi muncul pada abad ke- ....','tipe':'pg',
  'opsi':['18.','19.','20.','21.','22.'],'jawaban':1,
  'pembahasan':'Sosiologi lahir sebagai ilmu terpisah pada abad ke-19, dipopulerkan Auguste Comte pada masa perubahan besar akibat Revolusi Industri dan Revolusi Prancis.',
  'sumber':SRC%('5','B')},
 {'soal':'Dalam ilmu sosiologi dijelaskan bahwa sosiologi adalah ilmu positif mengenai masyarakat. Berikut pengertian ilmu sosiologi menurut ....','tipe':'pg',
  'opsi':['Karl Benz.','Auguste Comte.','Max Weber.','Selo Soemardjan.','Soelaeman Soemardi.'],'jawaban':1,
  'pembahasan':'Auguste Comte menyebut sosiologi sebagai ilmu POSITIF: mempelajari masyarakat berdasarkan fakta dan metode ilmiah, bukan spekulasi. (Karl Benz adalah penemu mobil — pengecoh nama!)',
  'sumber':SRC%('6','B')},
 {'soal':'Fungsi ilmu sosiologi yaitu untuk ilmu pendidikan artinya ....','tipe':'pg',
  'opsi':['menimbulkan masalah sosial.','tidak mengalami sebuah perubahan sosial.','untuk memahami dan menumbuhkan sikap kritis terhadap masalah sosial.','tidak menghasilkan kualitas sumber daya manusia yang lebih baik.','usaha untuk menentang pihak lawan.'],'jawaban':2,
  'pembahasan':'Dalam pendidikan, sosiologi membantu siswa memahami realitas sosial dan MENUMBUHKAN SIKAP KRITIS terhadap masalah sosial seperti kemiskinan, konflik, dan perubahan sosial.',
  'sumber':SRC%('7','C')},
 {'soal':'Adanya sebuah halte bus sebagai tempat pemberhentian para penumpang untuk melanjutkan sebuah perjalanan. Maka pembangunan halte bus tersebut membutuhkan sebuah fungsi ilmu sosiologi yaitu fungsi ....','tipe':'pg',
  'opsi':['pendidikan.','memecahkan masalah sosial.','menjaga perdamaian sosial.','perencanaan sosial.','memperbaiki kehidupan ekonomi masyarakat.'],'jawaban':3,
  'pembahasan':'Pembangunan halte bus = contoh penerapan sosiologi dalam PERENCANAAN SOSIAL: mempertimbangkan kebutuhan masyarakat dalam mobilitas sehari-hari secara lateral.',
  'sumber':SRC%('8','D')},
 {'soal':'Budi harus mendasarkan pendapatnya pada kenyataan yang ada di lapangan; apa yang ia temukan menjadi data yang bisa dipertanggungjawabkan. Pernyataan di atas merupakan ciri sosiologi yaitu .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['empiris.','nyata.','kumulatif.','nonetis.','nonrasional.'],'jawaban':[0,1],
  'pembahasan':'Empiris = berdasarkan fakta nyata di lapangan; data harus dapat diuji dan dipertanggungjawabkan secara ilmiah sesuai temuan nyata di titik riset. Kunci bank: A (empiris) dan B (nyata).',
  'sumber':SRC%('10','A,B')},
 {'soal':'Tim Sosiolog UNJ diminta pendapatnya oleh Pemerintah Kota Depok Jawa Barat untuk rencana pembangunan fly over untuk melewati perlintasan sebidang KRL Jakarta Bogor. Profesi sosiologi yang tepat adalah .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['konsultan.','penasihat.','peneliti.','guru.','praktisi.'],'jawaban':[0,1],
  'pembahasan':'Ketika sosiolog dimintai pendapat oleh pemerintah, perannya adalah KONSULTAN sekaligus PENASIHAT: memberi masukan dalam kebijakan sosial ("peramal kebijakan sosial").',
  'sumber':SRC%('12','A,B')},
 {'soal':'Sosiolog yang terjun langsung dalam program pemberdayaan masyarakat disebut .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['konsultan.','praktisi.','pendidik.','teoretikus.','applied Sociologist.'],'jawaban':[1,4],
  'pembahasan':'Sosiolog yang terjun langsung di lapangan untuk menyelesaikan masalah sosial tentatif dan meningkatkan kualitas warga = PRAKTISI / APPLIED SOCIOLOGIST.',
  'sumber':SRC%('13','B,E')},
 {'soal':'Dosen sosiologi kampus negeri X melakukan riset. Terdapat kesimpulan yang merevisi teori yang diajukan oleh peneliti sebelumnya dan dosen tersebut melakukannya berdasarkan kenyataan yang ada di lokasi penelitian. Ciri sosiologi sebagai ilmu yang tepat adalah .... (Jawaban bisa lebih dari satu)','tipe':'pgMulti',
  'opsi':['empiris.','represif.','nonetis.','kumulatif.','eksploratif.'],'jawaban':[0,3],
  'pembahasan':'Berdasarkan kenyataan lokasi = EMPIRIS; merevisi teori peneliti sebelumnya = KUMULATIF (teori baru memperbaiki teori lama). Kunci bank: A, D.',
  'sumber':SRC%('17','A,D')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah berdasarkan pernyataan berikut! (Tokoh sosiologi: klasik/modern)','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['Karl Marx merupakan salah satu tokoh sosiologi klasik.','Niccolo Machiavelli adalah salah seorang tokoh sosiologi modern.','Pierre Bourdieu adalah salah seorang tokoh sosiologi klasik.'],
  'jawaban':[0,1,1],
  'pembahasan':'Marx = tokoh sosiologi klasik (BENAR). Machiavelli bukan tokoh sosiologi (ia pemikir politik) apalagi modern (SALAH). Bourdieu = tokoh sosiologi MODERN, bukan klasik (SALAH). Kunci bank: B, S, S.',
  'sumber':SRC%('18','B,S,S')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: dua tokoh sosiologi yang mendefinisikan sosiologi sebagai ilmu tentang interaksi sosial adalah ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['John Philip Gillin','John Lewis Gillin','JP. Morgan','Emile Durkheim'],
  'jawaban':[0,0,1,1],
  'pembahasan':'Definisi sosiologi sebagai ilmu tentang interaksi sosial dikemukakan pasangan Gillin & Gillin (John Philip Gillin dan John Lewis Gillin) -> dua baris pertama BENAR. JP Morgan dan Durkheim tidak mendefinisikan demikian -> SALAH. Kunci bank: B, B, S, S.',
  'sumber':SRC%('21','B,B,S,S')},
 {'soal':'Berilah tanda centang pada kolom Benar atau Salah: dalam mengumpulkan data dan membuat laporan riset, dapat digunakan beberapa metode penelitian sosiologi. Metode itu dibagi menjadi dua, yaitu ....','tipe':'tabel',
  'kolom':['Benar','Salah'],
  'baris':['empiris dan nonetis.','kualitatif.','kuantitatif.','teortitis.'],
  'jawaban':[1,0,0,1],
  'pembahasan':'Metode penelitian sosiologi dibagi dua: KUALITATIF (mendalam) dan KUANTITATIF (angka) -> baris 2 & 3 BENAR. "Empiris dan nonetis" adalah CIRI ilmu, bukan metode (SALAH); "teortitis" bukan istilah metode (SALAH). Kunci bank: S, B, B, S.',
  'sumber':SRC%('23','S,B,B,S')},
 {'soal':'Pandangan bahwa masyarakat digerakkan oleh pertentangan kepentingan antara kelas borjuis dan proletar sehingga konflik menjadi mesin perubahan sosial berasal dari tokoh ....','tipe':'pg',
  'opsi':['Auguste Comte.','Karl Marx.','Emile Durkheim.','Max Weber.','Selo Soemardjan.'],'jawaban':1,
  'pembahasan':'Karl Marx: konflik kelas borjuis vs proletar dalam kapitalisme adalah motor perubahan sosial (terkonfirmasi juga di kunci Prediksi sosiologi no. 29).',
  'sumber':DR%('tokoh & teori konflik')},
 {'soal':'Pasangkan setiap tokoh sosiologi dengan sumbangan pemikiran yang paling tepat!','tipe':'jodoh',
  'premis':['Auguste Comte','Karl Marx','Emile Durkheim','Max Weber'],
  'opsi':['Menamai sosiologi dan menuntut kajian positif berbasis fakta','Teori konflik kelas sebagai mesin perubahan','Fakta sosial yang memaksa individu & solidaritas','Memahami tindakan sosial lewat makna (verstehen)','Snowball sampling untuk populasi tertutup'],
  'jawaban':[0,1,2,3],
  'pembahasan':'Comte = penamaan & positivisme; Marx = konflik kelas; Durkheim = fakta sosial & solidaritas; Weber = tindakan sosial & makna. Pengecoh: snowball sampling adalah teknik sampling modern, bukan sumbangan tokoh klasik.',
  'sumber':DR%('format menjodohkan tokoh')},
 {'soal':'Buku berjudul "Cours de Philosophie Positive" yang menjadi tonggak kelahiran sosiologi ditulis oleh ....','tipe':'isian',
  'jawaban':'Auguste Comte','hintFormat':'Tulis nama tokoh, contoh: Max Weber',
  'pembahasan':'Auguste Comte (1798-1857) menulis "Cours de Philosophie Positive" — buku yang memuat nama sosiologi untuk pertama kalinya.',
  'sumber':DR%('isian sejarah sosiologi')},
 {'soal':'Jelaskan empat ciri ilmu sosiologi (empiris, teoretis, kumulatif, nonetis) dan berikan SATU contoh tindakan peneliti yang melanggar ciri nonetis!','tipe':'uraian',
  'jawaban':'Rubrik: (1) Empiris = berdasarkan fakta lapangan; (2) Teoretis = menyusun kesimpulan sebab-akibat dari observasi; (3) Kumulatif = teori baru memperbaiki teori lama; (4) Nonetis = tidak menghakimi baik-buruk fakta. Contoh pelanggaran nonetis: peneliti menulis laporan yang menyebut pelaku tawuran "anak jahat yang pantas dihukum" alih-alih menganalisis faktor penyebab tawuran.',
  'pembahasan':'Kunci pengerjaan: sebut definisi tiap ciri dengan kata kuncimu sendiri, lalu beri contoh pelanggaran nonetis berupa penilaian moral pada objek penelitian — bukan analisis faktor.',
  'sumber':DR%('uraian empat ciri')},
]
b['ujiPemahaman']=Q
json.dump(d,open(p,'w'),ensure_ascii=False,indent=2)
from collections import Counter
print('soal bab1 sosiologi:',len(Q),Counter(k['tipe'] for k in Q))
